version: '3.4'

# define all the services using `services`
services:
  # name your website service 
  web-app:
    # specify what files and folders to take for building image using `build` key
    build:
      # specify files and folders location using `context`
      context: .
      # specifying dockerfile location using `dockerfile`
      dockerfile: ./Dockerfile

    # Alternate way to specify build 
    # build : .

    # Specify ports using `ports` 
    ports:
    # - host:container
      - 8000:8000
